version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
  version: 3.7
  system_packages: true
  install:
    - path: .
    - requirements: requirements_rtd.txt
